version:
jobs:
  build:
    docker:
      - image: circleci/python:3.8-buster-node-browsers-legacy
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3.8 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3.8 example_project/manage.py test
      - store_artifacts:
          path: test-reports/
          destination: example_project
      - run:
          command: |
            pip install pre-commit
            pre-commit install
      - run:
          name: "Running static code analysis"
          command: bin/pre_commit.sh
